package com.eclecticlogic.pedal.forward.dm;

// Generated May 28, 2014 8:44:27 AM by Hibernate Tools 4.3.1

import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * ExoticTypes generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "exotic_types")
public class ExoticTypes implements java.io.Serializable {

    private String login;
    private List<Boolean> countries;
    private Set<String> authorizations;
    private List<Long> scores;
    private Status status;


    @Id
    @Column(name = "login", unique = true, nullable = false)
    public String getLogin() {
        return this.login;
    }


    public void setLogin(String login) {
        this.login = login;
    }


    @Column(name = "countries", nullable = false)
    @Type(type = "com.eclecticlogic.pedal.provider.hibernate.dialect.PostgresqlBitStringUserType")
    public List<Boolean> getCountries() {
        return this.countries;
    }


    public void setCountries(List<Boolean> countries) {
        this.countries = countries;
    }


    @Column(name = "authorizations", nullable = false)
    @Type(type = "com.eclecticlogic.pedal.provider.hibernate.dialect.PostgresqlArrayToSetUserType$STRING")
    public Set<String> getAuthorizations() {
        return this.authorizations;
    }


    public void setAuthorizations(Set<String> authorizations) {
        this.authorizations = authorizations;
    }


    @Column(name = "scores", nullable = false)
    @Type(type = "com.eclecticlogic.pedal.provider.hibernate.dialect.PostgresqlArrayToListUserType$LONG")
    public List<Long> getScores() {
        return this.scores;
    }


    public void setScores(List<Long> scores) {
        this.scores = scores;
    }


    @Column(name = "status", nullable = false, length = 2)
    @Convert(converter = StatusConverter.class)
    public Status getStatus() {
        return status;
    }


    public void setStatus(Status status) {
        this.status = status;
    }

}
